In [60]:
# Torch
%load_ext autoreload
%autoreload 2
from env.simple_env import SimpleEnv
from tensordict import TensorDict

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [61]:
from torchrl.envs import check_env_specs, step_mdp

env = SimpleEnv()
check_env_specs(env)

2024-02-25 21:06:44,346 [torchrl][INFO] check_env_specs succeeded!


pos 0
x y coordtensor([0, 0])
action tensor([1, 0])
new xy tensor([1, 0])
new coords tensor([[10]])
tensor([[0.2000]])
pos 10
x y coordtensor([1, 0])
action tensor([ 0, -1])
new xy tensor([1, 0])
new coords tensor([[10]])
tensor([[0.2000]])
pos 10
x y coordtensor([1, 0])
action tensor([0, 1])
new xy tensor([1, 1])
new coords tensor([[11]])
tensor([[0.4000]])


In [ ]:
print(env.observation_spec)
print(env.action_spec)
print(env.reward_spec)
print(env.state_spec)

In [59]:
td = env.rand_step()
print(td)

pos 11
x y coordtensor([1, 1])
action tensor([ 0, -1])
new xy tensor([1, 0])
new coords tensor([[10]])
tensor([[0.4000]])
TensorDict(
    fields={
        action: Tensor(shape=torch.Size([1, 1]), device=cpu, dtype=torch.int64, is_shared=False),
        next: TensorDict(
            fields={
                ag_pos: Tensor(shape=torch.Size([1, 1]), device=cpu, dtype=torch.int64, is_shared=False),
                done: Tensor(shape=torch.Size([1, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                reward: Tensor(shape=torch.Size([1, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                terminated: Tensor(shape=torch.Size([1, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                visited_tile: Tensor(shape=torch.Size([1, 100]), device=cpu, dtype=torch.int64, is_shared=False)},
            batch_size=torch.Size([1]),
            device=None,
            is_shared=False)},
    batch_size=torch.Size([1]),
    device=None,
    is_shared=False)


In [64]:
## Omit transform for now
def simple_rollout(steps=100):
    # preallocate:
    data = TensorDict({}, (1,))
    # reset
    _data = env.reset()
    for i in range(steps):
        _data["action"] = env.action_spec.rand()
        _data = env.step(_data)
        data[i] = _data
        _data = step_mdp(_data, keep_other=True)
    return data


print("data from rollout:", simple_rollout(100))

pos 0
x y coordtensor([0, 0])
action tensor([ 0, -1])
new xy tensor([0, 0])
new coords tensor([[0]])
tensor([[0.]])
pos 0
x y coordtensor([0, 0])
action tensor([ 0, -1])
new xy tensor([0, 0])
new coords tensor([[0]])
tensor([[0.]])


IndexError: index 1 is out of bounds for dimension 0 with size 1